---
- name: Directory Exists | fluentd config roots
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: wcadmin
    mode: 775
  with_items:
    - "{{ fluentd_runtime_root }}"
    - "{{ fluentd_config_root }}"
    - "{{ fluentd_config_include_root }}"
    - "{{ fluentd_posfile_path }}"
  tags:
    - directory-structure
    - configuration
    - ansible

- name: "Upload Config | endpoint config"
  template:
    src: usr/local/etc/fluentd/fluentd.conf
    dest: "{{ fluentd_config_path }}"
    owner: root
    group: wcadmin
    mode: 0664
  notify: Reload Service | fluentd

- name: "Upload Config | sources config"
  template:
    src: usr/local/etc/fluentd/conf.d/sources.conf
    dest: "{{ fluentd_config_include_root }}/sources.conf"
    owner: root
    group: wcadmin
    mode: 0664
  when: fluentd_sources is iterable
  notify: Reload Service | fluentd
